version: '3.8'
services:
  db:
    container_name: db_postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - webnet

  backend:
    container_name: backend
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    volumes:
      - ./backend:/var/www
    networks:
      - webnet

  frontend:
    container_name: frontend
    build:
     context: frontend/
     dockerfile: Dockerfile
    volumes:
     - './frontend:/app'
     - 'node_modules:/app/node_modules'
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    networks:
      - webnet

  nginx:
    build:
      context:  .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend
    networks:
      - webnet

volumes:
  postgres-data:
  node_modules:

networks:
  webnet: