security:
  password_hashers:
    # Our user class and the algorithm we'll use to encode passwords
    # 'auto' means to let Symfony choose the best possible password hasher (Argon2 or Bcrypt)
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

  providers:
    database_users:
      entity:
        class: App\Entity\User
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      # this firewall does not have a 'pattern' option because it applies to all URLs
      lazy: true
      provider: database_users

    api:
      pattern: ^/api
      stateless: true
      jwt: ~

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
    - { path: ^/profile, roles: ROLE_USER }
